version: 2
jobs:
  test:
    working_directory: ~/origami-repo-data
    docker:
      - image: node:8
      - image: postgres:9.6
        environment:
          - POSTGRES_USER=origami
          - POSTGRES_DB=origami-repo-data-test
    environment:
      TEST_DATABASE: "postgres://origami@localhost:5432/origami-repo-data-test"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Node.js dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run linters
          command: make verify
      - run:
          name: Run unit tests
          command: make test-unit-coverage
      - run:
          name: Run integration tests
          command: make test-integration
workflows:
  version: 2
  test:
    jobs:
      - test
